name: Selenium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Check Chrome
      shell: powershell
      run: |
        if (Get-Command "chrome" -ErrorAction SilentlyContinue) {
          Write-Host "Chrome is available"
        } else {
          Write-Host "Chrome not found - please install"
          if (-not (Get-Command "chrome" -ErrorAction SilentlyContinue)) {
            $chromeUrl = "https://dl.google.com/chrome/install/chrome_installer.exe"
            $chromeInstaller = "$env:TEMP\chrome_installer.exe"
            Write-Host "Downloading Chrome..."
            Invoke-WebRequest -Uri $chromeUrl -OutFile $chromeInstaller
            Write-Host "Installing Chrome..."
            Start-Process -FilePath $chromeInstaller -ArgumentList "/silent", "/install" -Wait
          }
        }
        
    - name: Run tests
      shell: powershell
      run: mvn clean test -Dtest=MainRunner
      
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/
