name: Selenium Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Run tests
      run: mvn clean test -Dtest=MainRunner
      env:
        DISPLAY: :99
      
    - name: Generate Allure Report
      run: |
        wget -q https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.tgz
        tar -xzf allure-2.17.3.tgz
        ./allure-2.17.3/bin/allure generate target/allure-results --clean -o allure-report
      if: always()
      
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
